### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by floradu88** [stevegreatrex/ProxyApi#10]
Is this still maintained?

If not is there any way of continuing the work on this?

**Comment by stevegreatrex** [comment]
It is still maintained (theoretically) but I haven't had the need to add
any features recently!

I'm very happy for you to join in and help with maintenance though - what
would you be interested in adding?

**Comment by floradu88** [comment]
I want to use it in some projects, and if needed, I might want to fix bugs, if there are any :)
